version: '3.5'
name: evaluating_material_app

networks: 
  inside_net:
    name: inside_net
    driver: bridge

services: 
  nginx_proxy:
    image: nginx:1.25.2
    container_name: nginx_proxy
    ports: 
      - '${APP_PROXY_PORT}:${APP_PROXY_PORT}'
    environment: 
      - 'APP_PROXY_PORT=${APP_PROXY_PORT}'
      - 'APP_PROXY_HOST=${APP_PROXY_HOST}'
      - 'APP_HOST=app'
      - 'APP_PORT=${APP_PORT}'
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./static:/static:ro
    depends_on: 
      - app
    networks: 
      - inside_net

  app: 
    build: .
    container_name: app
    environment: 
      - 'NODE_ENV=${NODE_ENV}'
      - 'APP_PROXY_HOST=${APP_PROXY_HOST}'
      - 'APP_PROXY_PORT=${APP_PROXY_PORT}'
      - 'APP_PORT=${APP_PORT}'
      - 'DB_HOST=postgres_db'
      - 'DB_PASSWORD=${DB_PASSWORD}'
    depends_on: 
      - postgres_db
    volumes:
      - ./static:/usr/app/evaluationgMaterial-App/static
    networks: 
      - inside_net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment: 
      - 'ADMINER_DEFAULT_SERVER=postgres_db:5432'
    networks: 
      - inside_net

  postgres_db: 
    image: postgres:16.0
    container_name: postgres_db
    environment: 
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
      - 'POSTGRES_DB=${DB_NAME}'
    volumes: 
      - ./${DB_NAME}.gz:/var/backups/${DB_NAME}.gz:ro
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - ./postgres_data:/var/lib/postgresql/data
    networks: 
      - inside_net


