version: '3.5'
name: evaluating_material_app

networks: 
  inside_net:
    name: inside_net
    driver: bridge

services: 

  app: 
    build: .
    container_name: app
    ports:
      - 80:9090
    environment: 
      - 'APP_PORT=9090'
      - 'DB_HOST=postgres_db'
    depends_on: 
      - postgres_db
    volumes:
      - ./static:/usr/app/evaluationgMaterial-App/static
    networks: 
      - inside_net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment: 
      - 'ADMINER_DEFAULT_SERVER=postgres'
    networks: 
      - inside_net

  postgres_db: 
    image: postgres:16.0
    container_name: postgres_db
    environment: 
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=evaluating_material_app_db'
    volumes: 
      - ./evaluating_material_app_db.gz:/var/backups/evaluating_material_app_db.gz
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks: 
      - inside_net


