
name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
      
    - name: Installing dependencies...
      run: npm i

    - name: Building project...
      run: npm run build --if-present

    - name: Running deployment script with SSH
      run: |
        chmod u+x show_all.sh
        ./deployScript
